### ISSUE TITLE
 msg: 'Connections: undefined not found.' }  POST /onboarding/create 200 in 864ms

### ISSUE THREAD

**Issue by muchemwal** [auth0-developer-hub/auth0-b2b-saas-starter#53]
#### Node.js and npm/yarn Versions
- **Node.js version**: `v20.16.0`
- **npm version**: `10.8.1`

#### Operating System
- **OS**: macOS Sonoma 14.5

![image](https://github.com/user-attachments/assets/cb9ac05b-258c-4dee-b24e-b629e558ac3d)

hi all, I followed the guide in setting up this starter app but i am getting the error below on creating an organization:

failed to create an organization ManagementApiError: Connections: undefined not found.
    at OrganizationsManager.parseError (webpack-internal:///(action-browser)/./node_modules/auth0/dist/esm/management/management-client.js:38:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OrganizationsManager.request (webpack-internal:///(action-browser)/./node_modules/auth0/dist/esm/lib/runtime.js:116:23)
    at async OrganizationsManager.create (webpack-internal:///(action-browser)/./node_modules/auth0/dist/esm/management/__generated/managers/organizations-manager.js:440:26)
    at async createOrganization (webpack-internal:///(action-browser)/./app/onboarding/create/actions.ts:30:35)
    at async ..//auth0-b2b-saas-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
    at async rw (..//auth0-b2b-saas-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
    at async r6 (..//auth0-b2b-saas-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1256)
    at async doRender (..//auth0-b2b-saas-starter/node_modules/next/dist/server/base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (..//auth0-b2b-saas-starter/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (..//auth0-b2b-saas-starter/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (..//auth0-b2b-saas-starter/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (..//auth0-b2b-saas-starter/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (..//auth0-b2b-saas-starter/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (..//auth0-b2b-saas-starter/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (..//auth0-b2b-saas-starter/node_modules/next/dist/server/base-server.js:816:17)
    at async ..//auth0-b2b-saas-starter/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (..//auth0-b2b-saas-starter/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (..//auth0-b2b-saas-starter/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (..//auth0-b2b-saas-starter/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (..//auth0-b2b-saas-starter/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (..//auth0-b2b-saas-starter/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (..//auth0-b2b-saas-starter/node_modules/next/dist/server/lib/start-server.js:141:13) {
  errorCode: 'inexistent_connection',
  error: 'Not Found',
  statusCode: 404,
  body: '{"statusCode":404,"error":"Not Found","message":"Connections: undefined not found.","errorCode":"inexistent_connection"}',
  headers: Headers {
    date: 'Fri, 16 Aug 2024 10:51:53 GMT',
    'content-type': 'application/json; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'keep-alive',
    'cf-ray': '8b40df2bf9bf055e-JNB',
    'cf-cache-status': 'DYNAMIC',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    vary: 'origin, Accept-Encoding',
    'access-control-expose-headers': 'WWW-Authenticate,Server-Authorization',
    'x-content-type-options': 'nosniff',
    server: 'cloudflare',
    'content-encoding': 'br',
    'alt-svc': 'h3=":443"; ma=86400'
  },
  msg: 'Connections: undefined not found.'
}
 POST /onboarding/create 200 in 836ms

**Comment by muchemwal** [comment]
I figured it out, the DEFAULT_CONNECTION_ID was not set by the bootstrap, i have to manually enter it, now it works fine
